# OpenAPI Generator config (go)
# Generated output goes to: sdks/go
packageName: paystack
moduleName: github.com/alexasomba/paystack-go
packageVersion: 1.1.1
gitHost: github.com
gitUserId: alexasomba
gitRepoId: paystack-openapi/sdks/go
hideGenerationTimestamp: true
